### ISSUE TITLE
vector files for qiicr logos

### ISSUE THREAD

**Issue by pieper** [QIICR/ProjectIssuesAndWiki#13]
@fedorov, can you put the original logo files somewhere, perhaps in a logos repository of the github qiicr organization.  That way we can grab the right one in the future when needed for a poster or presentation.

**Comment by fedorov** [comment]
Uploaded to QIICR/Public/Logo on Midas. SVGs are not ideal, because they depend on a non-standard font and do not render correctly unless the font is installed. I will need to convert to paths in Inkscape and save a new version (it's easier for me to do this on a linux machine in the office).

**Comment by rkikinis** [comment]
+1

**Comment by fedorov** [comment]
Will work on this today

**Comment by pieper** [comment]
Maybe also upload a pdf version.

**Comment by fedorov** [comment]
PDF, PNG and SVG added here: https://github.com/QIICR/ProjectIssuesAndWiki/wiki/Presentation-resources-and-logos
