### ISSUE TITLE
find or create and example dicom objects, starting with spatial registration objects

### ISSUE THREAD

**Issue by pieper** [QIICR/ProjectIssuesAndWiki#14]
I plan to ask around at RSNA for sample datasets of various types (registration, segmentation, surfaces...).  Last time I asked around, it seems that many of the objects exist only in the spec and there are no concrete instantiations or systems that produce them.  If this is still the case I will try to make some files that are consistent with the spec, starting with registration objects.

**Comment by fedorov** [comment]
SPL Brain atlas 2013 segmentation object is here: http://slicer.kitware.com/midas3/folder/1896

Registration object earlier shared by Greg in the SlicerRT data repository: https://www.assembla.com/code/slicerrt/subversion/nodes/1284/trunk/SlicerRt/data/MIM-6.0-spatial-registration-objects

I can also try to generate them with syngo.via, I am pretty sure it does that, but need to choose the right workflow on the right data (longitudinal PET/CT should trigger it I think).

**Comment by pieper** [comment]
Thanks Andrey!  I will look at these.

**Comment by fedorov** [comment]
I am sure @dclunie will have more pointers!

**Comment by mehrtash** [comment]
@fedorov It looks like that the compressed file for SPL brain atlas is broken. Would you please check it?

**Comment by fedorov** [comment]
Indeed, the file was incomplete. I re-uploaded, it should be fixed now.

**Comment by fedorov** [comment]
QIICR Midas community now has samples of SEG, REG, RWVM, SR, enhanced multiframe objects. I upload the datasets as they become available. Pointers to relevant external datasets are also available from related wiki pages.
