### ISSUE TITLE
Using MIDAS for sharing DICOM data and wiki content

### ISSUE THREAD

**Issue by fedorov** [QIICR/ProjectIssuesAndWiki#3]
Set up an organization on Midas? http://slicer.kitware.com/midas3

**Comment by fedorov** [comment]
@rkikinis

**Comment by fedorov** [comment]
Is it possible to have private collections?

**Comment by fedorov** [comment]
@rkikinis Can we create a QIICR community on Slicer Midas, and have both public and private collections in that community?

**Comment by jcfr** [comment]
All set. Community created and @fedorov  set as administrator. See http://slicer.kitware.com/midas3/community/27

**Comment by fedorov** [comment]
@QIICR/qiicr-team: we created a dedicated project space for QIICR on this instance of Midas: http://slicer.kitware.com/midas3/community/27

If you don't have an account, please register and request access to QIICR community.

![image](https://f.cloud.github.com/assets/313942/1411962/375e2302-3dc3-11e3-99e7-6e2b37471d92.png)

We will use Public folder for linking content to wiki, and Private folder for the documents that are not ready for sharing outside the project team. Slides from Fiona, Jayashree and Reinhard have been uploaded to the private folder already.

**Comment by pieper** [comment]
I don't see the "Join the community" button:

![image](https://f.cloud.github.com/assets/126077/1412739/6b2901f4-3de9-11e3-88bd-4c62e500f83f.png)

I am logged in with my account and I can see the qiicr community but I can also see that I am not on the list of members.  What's up?

**Comment by rkikinis** [comment]
are you logged in?

On 10/25/13, 10:51 PM, Steve Pieper wrote:

> I don't see the "Join the community" button:
> 
> image
> https://f.cloud.github.com/assets/126077/1412739/6b2901f4-3de9-11e3-88bd-4c62e500f83f.png
> 
> I am logged in with my account and I can see the qiicr community but I
> can also see that I am not on the list of members. What's up?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/QIICR/ProjectIssuesAndWiki/issues/3#issuecomment-27137791.

## 

Ron Kikinis, M.D.,
Robert Greenes Distinguished Director of Biomedical Informatics
Professor of Radiology, Harvard Medical School
Director, Surgical Planning Laboratory
http://www.spl.harvard.edu/~kikinis

The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by fedorov** [comment]
@jcfr do you know what is wrong?

Of course I can add Steve by name, but maybe something needs to be done to enable the "Join community" button? I see it for the ITK community, when I view it.

**Comment by pieper** [comment]
Yes, I was logged on before.

I just got an invitation email and then when I went back to the page the
button was there and it seems to have worked.  Now that I'm in the
community I can see the private data.

**Comment by fedorov** [comment]
Steve, I added you manually. I will do this for the whole team. I am not a member of ITK community, and I don't think I was invited, but I do see the "join" button.

**Comment by pieper** [comment]
Probably there's a configuration for 'by invitation only' since we have
private data.  Maybe ITK has only public data.

**Comment by jcfr** [comment]
When I created the community, I defined the community as "Join only by
invitation".
I just change this in the settings (Manage -> Privacy) so that anybody
could join.
Hth
Jc

On Fri, Oct 25, 2013 at 11:25 PM, Steve Pieper notifications@github.comwrote:

> Probably there's a configuration for 'by invitation only' since we have
> private data. Maybe ITK has only public data.
> 
> On Fri, Oct 25, 2013 at 11:07 PM, Andrey Fedorov
> notifications@github.comwrote:
> 
> > Steve, I added you manually. I will do this for the whole team. I am not
> > a
> > member of ITK community, and I don't think I was invited, but I do see
> > the
> > "join" button.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/QIICR/ProjectIssuesAndWiki/issues/3#issuecomment-27138167>
> > 
> > .
> > 
> > The information in this e-mail is intended only for the person to whom
> > it
> > is
> > addressed. If you believe this e-mail was sent to you in error and the
> > e-mail
> > contains patient information, please contact the Partners Compliance
> > HelpLine at
> > http://www.partners.org/complianceline . If the e-mail was sent to you
> > in
> > error
> > but does not contain patient information, please contact the sender and
> > properly
> > dispose of the e-mail.
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/QIICR/ProjectIssuesAndWiki/issues/3#issuecomment-27138496
> .

## 

+1 919 869 8849

**Comment by pieper** [comment]
Hi Jc -

I think the previous setting is probably what we wanted but we just didn't
understand it.  We want to use the community to store both public and
private data, so we want to approve all joining activity.

But maybe what we were expecting is a 'Request to Join Community" button
and not just a blank space.  Is there such an option?

Maybe we should just put it in the community description a note like: "If
you wish to access private content of this community, please email
fedorov@bwh.harvard.edu"  (ultimately we can set up mail for qiicr.org but
I don't think we have that yet).

-Steve

**Comment by jcfr** [comment]
@cpatrick @zachmullen What do you think ? Would it make sense to add a "Request to Join Community" for community that expect their users to be invited ?

**Comment by rbeichel** [comment]
Hi Andriy,

I'm now registered. Can you please add me to the group?

Thanks,
Reinhard

On 10/25/13 22:07, Andrey Fedorov wrote:

> Steve, I added you manually. I will do this for the whole team. I am not
> a member of ITK community, and I don't think I was invited, but I do see
> the "join" button.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/QIICR/ProjectIssuesAndWiki/issues/3#issuecomment-27138167.

## 

Reinhard R. Beichel, PhD | Associate Professor | The University of Iowa
Dept. of Electrical & Computer Engineering | Dept. of Internal Medicine
Phone: (+1) (319) 335-4597 | http://www.engineering.uiowa.edu/~rbeichel

**Comment by fedorov** [comment]
All members of the QIICR github team have now been added to the QIICR Midas project (by name or by email).

**Comment by fedorov** [comment]
@rbeichel : can you upload the videos you reference from your presentation into the private area of Midas for our reference?

**Comment by cpatrick** [comment]
@jcfr, I think a feature like that would be great. I added it to the issue tracker [here](http://public.kitware.com/MidasBT/view.php?id=1038).
