### ISSUE TITLE
TCIA for immediate data sharing needs

### ISSUE THREAD

**Issue by fedorov** [QIICR/ProjectIssuesAndWiki#8]

**Comment by fedorov** [comment]
@rbeichel you mentioned you went through the process of requesting support from TCIA to host a dataset for your challenge. Do you think you could email me the response you received from TCIA (or just post it here, if you feel fine with that)?

**Comment by rbeichel** [comment]
Andriy,

I have asked in the context of mouse lung image analysis. Consequently, 
it was not QIN related. Anyway, you can find the text regarding 
"fee-for-service model" below.

Reinhard

---

Reinhard - Thank you for your interest in leveraging TCIA for your 
research activity.  I will raise this topic at our advisory board 
meeting early next week and get back to you.  Currently there are only 
invivo images on TCIA, and mice imaging may present particular 
challenges in DICOM, although of course there are solutions.  Do you 
know if the R01 would cover curation and hosting costs for the data? 
TCIA is migrating to a fee-for-service model in some cases so there may 
be some cost-recovery desired.  If the advisory board determines that 

## this is in line with TCIA's mission we could provide a cost estimate.

On 10/28/13 14:40, Andrey Fedorov wrote:

> @rbeichel https://github.com/rbeichel you mentioned you went through
> the process of requesting support from TCIA to host a dataset for your
> challenge. Do you think you could email me the response you received
> from TCIA (or just post it here, if you feel fine with that)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/QIICR/ProjectIssuesAndWiki/issues/8#issuecomment-27247954.

## 

Reinhard R. Beichel, PhD | Associate Professor | The University of Iowa
Dept. of Electrical & Computer Engineering | Dept. of Internal Medicine
Phone: (+1) (319) 335-4597 | http://www.engineering.uiowa.edu/~rbeichel

**Comment by fedorov** [comment]
As a result of discussions with TCIA personnel, the conclusion is TCIA is most suitable and should be used for sharing datasets of value to the community, not for everyday sharing. We have a preliminary agreement that the data corresponding to the processing results of the existing data (such as Iowa collection) will be ok to add to these collection.
